### ISSUE TITLE
同步印象笔记到hexo博客 | 布衣男儿

### ISSUE THREAD

**Issue by iT-Boyer** [huos3203/huos3203.github.io#43]
https://huosan.gitee.io/2018/10/19/hexo/%E5%90%8C%E6%AD%A5%E5%8D%B0%E8%B1%A1%E7%AC%94%E8%AE%B0%E5%88%B0hexo%E5%8D%9A%E5%AE%A2/ 

 不物喜，不己悲，善假物，易参行！

**Comment by eyesmoons** [comment]
good
